export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  oldPrice?: number;
  category: string;
  grams: number;
  kcal: number;
  ingredients: string;
  allergens: string;
  tone: string;
};

export type Menu = {
  slug: string;
  name: string;
  kind: string;
  address: string;
  availability: string;
  rating: number;
  ratingLabel: string;
  time: string;
  fee: string;
  intro: string;
  categories: string[];
  products: Product[];
  tone: string;
  swatch: string;
};

export const NAV = [
  { label: "Offres", href: "/offres" },
  { label: "Nouveautés", href: "/nouveautes" },
  { label: "Menus", href: "/menus" },
  { label: "Entreprises", href: "/entreprises" },
];

export const HERO_TILES = [
  {
    label: "Petits-déjeuners",
    href: "/menus/petits-dejeuners",
    tone: "from-[#ffe9a3] to-[#ffd400]",
    swatch: "#ffe9a3",
    note: "Livrés au bureau dès 7h",
  },
  {
    label: "Déjeuners",
    href: "/menus/dejeuners",
    tone: "from-[#ffd9b0] to-[#ffb454]",
    swatch: "#ffd9b0",
    note: "Plats chauds de midi",
  },
];

export const POPULAR_CATEGORIES = [
  { label: "Petit-déjeuner", href: "/menus/petits-dejeuners", tone: "#ffe9a3" },
  { label: "Déjeuner", href: "/menus/dejeuners", tone: "#ffd9b0" },
  { label: "Jus naturels", href: "/menus/jus-naturels", tone: "#ffe6c2" },
  { label: "Formules entreprise", href: "/menus/formules-entreprise", tone: "#e9edff" },
  { label: "Traiteur", href: "/menus/traiteur", tone: "#ffe0e0" },
  { label: "Snacks", href: "/menus/petits-dejeuners", tone: "#e6f5e2" },
  { label: "Desserts", href: "/menus/petits-dejeuners", tone: "#f3e6ff" },
  { label: "Végétarien", href: "/menus/dejeuners", tone: "#e2f3f5" },
];

export const SIZES = [
  "Individuel",
  "Duo",
  "Trio",
  "Petit",
  "Moyen",
  "Grand",
  "Plateau 10",
  "Plateau 20",
  "Buffet 50",
];

export const MENUS: Menu[] = [
  {
    slug: "petits-dejeuners",
    name: "Petits-déjeuners",
    kind: "Break du matin",
    address: "Bonapriso, Douala",
    availability: "Livraison en entreprise dès 7h",
    rating: 98,
    ratingLabel: "Parfait",
    time: "20-30 min",
    fee: "Gratuite",
    intro:
      "Des petits-déjeuners complets préparés le matin même et livrés directement à votre bureau.",
    categories: ["Bouillies", "Beignets", "Œufs", "Sandwichs", "Viennoiseries", "Fruits", "Boissons chaudes"],
    tone: "from-[#ffe9a3] to-[#ffd400]",
    swatch: "#ffe9a3",
    products: [
      {
        id: "pd-1",
        name: "Beignets Haricot Bouillie",
        description: "Le trio camerounais complet : beignets moelleux, haricot mijoté et bouillie de maïs.",
        price: 2500,
        oldPrice: 2800,
        category: "Beignets",
        grams: 520,
        kcal: 780,
        ingredients: "Farine de blé, haricot rouge, maïs, lait, huile végétale, sucre",
        allergens: "Gluten, lait",
        tone: "#ffe9a3",
      },
      {
        id: "pd-2",
        name: "Bouillie de maïs au lait",
        description: "Bouillie onctueuse de maïs blanc, lait concentré et une pointe de vanille.",
        price: 1200,
        category: "Bouillies",
        grams: 400,
        kcal: 320,
        ingredients: "Maïs blanc, lait concentré, vanille, sucre de canne",
        allergens: "Lait",
        tone: "#fff0cc",
      },
      {
        id: "pd-3",
        name: "Omelette spéciale Jojoo",
        description: "Trois œufs, légumes frais, fromage et pain frais de la boulangerie du quartier.",
        price: 2800,
        oldPrice: 3000,
        category: "Œufs",
        grams: 380,
        kcal: 610,
        ingredients: "Œufs, tomate, oignon, poivron, fromage, pain",
        allergens: "Œufs, lait, gluten",
        tone: "#ffe3b0",
      },
      {
        id: "pd-4",
        name: "Sandwich poulet avocat",
        description: "Pain complet, émincé de poulet mariné, avocat, crudités et sauce maison.",
        price: 3000,
        category: "Sandwichs",
        grams: 320,
        kcal: 540,
        ingredients: "Pain complet, poulet, avocat, salade, tomate, sauce maison",
        allergens: "Gluten, œufs, moutarde",
        tone: "#e6f5e2",
      },
      {
        id: "pd-5",
        name: "Pain perdu caramélisé",
        description: "Tranches dorées de brioche, caramel léger et éclats de cacahuètes.",
        price: 2000,
        oldPrice: 2300,
        category: "Viennoiseries",
        grams: 260,
        kcal: 480,
        ingredients: "Brioche, œufs, lait, sucre, cacahuètes",
        allergens: "Gluten, œufs, lait, arachides",
        tone: "#ffdca8",
      },
      {
        id: "pd-6",
        name: "Salade de fruits frais",
        description: "Ananas, mangue, papaye et pastèque coupés le matin même.",
        price: 1800,
        category: "Fruits",
        grams: 350,
        kcal: 210,
        ingredients: "Ananas, mangue, papaye, pastèque, citron vert",
        allergens: "Aucun",
        tone: "#ffe0e0",
      },
      {
        id: "pd-7",
        name: "Yaourt maison granola",
        description: "Yaourt nature préparé maison, granola croustillant et miel d'Adamaoua.",
        price: 2200,
        category: "Fruits",
        grams: 300,
        kcal: 390,
        ingredients: "Yaourt, avoine, miel, amandes, raisins secs",
        allergens: "Lait, fruits à coque, gluten",
        tone: "#f3e6ff",
      },
      {
        id: "pd-8",
        name: "Café ou thé + croissant",
        description: "Café filtre ou thé au choix, accompagné d'un croissant pur beurre.",
        price: 1500,
        oldPrice: 1700,
        category: "Boissons chaudes",
        grams: 280,
        kcal: 350,
        ingredients: "Café arabica ou thé, lait, sucre, croissant",
        allergens: "Gluten, lait",
        tone: "#efe4d8",
      },
    ],
  },
  {
    slug: "dejeuners",
    name: "Déjeuners",
    kind: "Repas de midi",
    address: "Akwa, Douala",
    availability: "Livraison en entreprise de 11h30 à 14h",
    rating: 96,
    ratingLabel: "Parfait",
    time: "25-40 min",
    fee: "Gratuite",
    intro:
      "Des plats chauds cuisinés le jour même, portions généreuses, livrés à l'heure de votre pause.",
    categories: ["Plats locaux", "Riz & pâtes", "Grillades", "Végétarien", "Salades", "Accompagnements", "Desserts"],
    tone: "from-[#ffd9b0] to-[#ffb454]",
    swatch: "#ffd9b0",
    products: [
      {
        id: "dj-1",
        name: "Poulet DG",
        description: "Poulet mijoté, plantains mûrs sautés et légumes croquants, la signature de la maison.",
        price: 5000,
        oldPrice: 5500,
        category: "Plats locaux",
        grams: 650,
        kcal: 890,
        ingredients: "Poulet, plantain, carotte, haricot vert, poivron, épices",
        allergens: "Céleri",
        tone: "#ffd9b0",
      },
      {
        id: "dj-2",
        name: "Ndolè aux crevettes",
        description: "Ndolè traditionnel aux arachides et crevettes fraîches, servi avec plantains.",
        price: 4500,
        category: "Plats locaux",
        grams: 600,
        kcal: 820,
        ingredients: "Feuilles de ndolè, arachides, crevettes, plantain, épices",
        allergens: "Arachides, crustacés",
        tone: "#dfe8d5",
      },
      {
        id: "dj-3",
        name: "Riz sauté au poulet",
        description: "Riz parfumé sauté au wok, dés de poulet, légumes et sauce soja légère.",
        price: 3500,
        oldPrice: 3800,
        category: "Riz & pâtes",
        grams: 550,
        kcal: 720,
        ingredients: "Riz, poulet, carotte, petits pois, sauce soja, ail",
        allergens: "Soja, gluten",
        tone: "#ffe9a3",
      },
      {
        id: "dj-4",
        name: "Poisson braisé plantain",
        description: "Maquereau braisé aux épices, plantains frits et sauce piment maison.",
        price: 5500,
        category: "Grillades",
        grams: 620,
        kcal: 760,
        ingredients: "Maquereau, plantain, oignon, piment, épices, citron",
        allergens: "Poisson",
        tone: "#ffd3c2",
      },
      {
        id: "dj-5",
        name: "Eru & water fufu",
        description: "Eru finement coupé, huile de palme rouge et water fufu moelleux.",
        price: 4000,
        category: "Plats locaux",
        grams: 580,
        kcal: 700,
        ingredients: "Feuilles d'eru, waterleaf, huile de palme, viande, poisson fumé",
        allergens: "Poisson, crustacés",
        tone: "#e2eddb",
      },
      {
        id: "dj-6",
        name: "Spaghetti sauce bolognaise",
        description: "Pâtes al dente, sauce tomate mijotée longuement et viande hachée.",
        price: 3200,
        oldPrice: 3500,
        category: "Riz & pâtes",
        grams: 500,
        kcal: 680,
        ingredients: "Spaghetti, tomate, bœuf haché, oignon, ail, basilic",
        allergens: "Gluten, céleri",
        tone: "#ffdcc8",
      },
      {
        id: "dj-7",
        name: "Salade César poulet",
        description: "Salade croquante, poulet grillé, croûtons dorés et sauce césar maison.",
        price: 3800,
        category: "Salades",
        grams: 420,
        kcal: 460,
        ingredients: "Laitue, poulet, parmesan, croûtons, œuf, sauce césar",
        allergens: "Gluten, œufs, lait, poisson",
        tone: "#e6f5e2",
      },
      {
        id: "dj-8",
        name: "Koki de maïs végétarien",
        description: "Koki de maïs cuit à la feuille, 100 % végétarien, servi avec plantain mûr.",
        price: 3000,
        category: "Végétarien",
        grams: 480,
        kcal: 540,
        ingredients: "Maïs frais, huile de palme, plantain, épices",
        allergens: "Aucun",
        tone: "#fff0cc",
      },
    ],
  },
  {
    slug: "jus-naturels",
    name: "Jus naturels",
    kind: "Pressés du jour",
    address: "Bonapriso, Douala",
    availability: "Livraison toute la journée",
    rating: 99,
    ratingLabel: "Parfait",
    time: "20-30 min",
    fee: "Gratuite",
    intro:
      "Des jus pressés le jour même, sans conservateur ni colorant, en bouteille de 50 cl ou 1 litre.",
    categories: ["Agrumes", "Tropicaux", "Détox", "Infusions", "Smoothies", "Sans sucre", "Format litre"],
    tone: "from-[#ffe6c2] to-[#ffcf5c]",
    swatch: "#ffe6c2",
    products: [
      {
        id: "js-1",
        name: "Jus de gingembre",
        description: "Gingembre frais pressé, citron et une pointe de miel, servi bien frais.",
        price: 1500,
        oldPrice: 1800,
        category: "Détox",
        grams: 500,
        kcal: 180,
        ingredients: "Gingembre, citron, miel, eau filtrée",
        allergens: "Aucun",
        tone: "#ffe9a3",
      },
      {
        id: "js-2",
        name: "Foléré (bissap) menthe",
        description: "Infusion d'hibiscus glacée, menthe fraîche et zeste d'ananas.",
        price: 1200,
        category: "Infusions",
        grams: 500,
        kcal: 150,
        ingredients: "Hibiscus, menthe, ananas, sucre de canne",
        allergens: "Aucun",
        tone: "#ffd0d8",
      },
      {
        id: "js-3",
        name: "Jus d'ananas frais",
        description: "Ananas pressé à froid, aucune eau ajoutée, sucré naturellement.",
        price: 1500,
        category: "Tropicaux",
        grams: 500,
        kcal: 210,
        ingredients: "Ananas frais",
        allergens: "Aucun",
        tone: "#ffe9a3",
      },
      {
        id: "js-4",
        name: "Jus de mangue",
        description: "Mangues mûres du pays mixées, texture veloutée et parfum intense.",
        price: 1800,
        oldPrice: 2000,
        category: "Tropicaux",
        grams: 500,
        kcal: 240,
        ingredients: "Mangue, citron vert, eau filtrée",
        allergens: "Aucun",
        tone: "#ffd9b0",
      },
      {
        id: "js-5",
        name: "Cocktail tropical",
        description: "Ananas, mangue, orange et fruit de la passion dans une seule bouteille.",
        price: 2000,
        category: "Tropicaux",
        grams: 500,
        kcal: 260,
        ingredients: "Ananas, mangue, orange, fruit de la passion",
        allergens: "Aucun",
        tone: "#ffdca8",
      },
      {
        id: "js-6",
        name: "Citron gingembre sans sucre",
        description: "Version sans sucre ajouté, idéale pour accompagner un déjeuner léger.",
        price: 1500,
        category: "Sans sucre",
        grams: 500,
        kcal: 90,
        ingredients: "Citron, gingembre, eau filtrée",
        allergens: "Aucun",
        tone: "#e6f5e2",
      },
      {
        id: "js-7",
        name: "Smoothie banane avocat",
        description: "Banane, avocat et lait, un smoothie crémeux et rassasiant.",
        price: 2200,
        category: "Smoothies",
        grams: 450,
        kcal: 380,
        ingredients: "Banane, avocat, lait, miel",
        allergens: "Lait",
        tone: "#e2f3f5",
      },
      {
        id: "js-8",
        name: "Pack 1 litre au choix",
        description: "Un litre du parfum de votre choix, parfait pour partager au bureau.",
        price: 3000,
        oldPrice: 3500,
        category: "Format litre",
        grams: 1000,
        kcal: 420,
        ingredients: "Selon le parfum choisi",
        allergens: "Selon le parfum choisi",
        tone: "#f3e6ff",
      },
    ],
  },
  {
    slug: "formules-entreprise",
    name: "Formules entreprise",
    kind: "Abonnements bureau",
    address: "Toute la ville de Douala",
    availability: "Commandes à l'avance ou avant 9h",
    rating: 97,
    ratingLabel: "Parfait",
    time: "Planifiée",
    fee: "Gratuite",
    intro:
      "Des formules pensées pour les équipes : facturation simple, livraison à heure fixe, menus variés chaque jour.",
    categories: ["Formules solo", "Formules équipe", "Abonnements", "Pauses café", "Réunions", "Sur mesure", "Végétarien"],
    tone: "from-[#e9edff] to-[#b9c6ff]",
    swatch: "#e9edff",
    products: [
      {
        id: "fe-1",
        name: "Formule Break Solo",
        description: "Un petit-déjeuner complet + une boisson chaude, livré chaque matin avant 8h.",
        price: 3000,
        oldPrice: 3500,
        category: "Formules solo",
        grams: 500,
        kcal: 620,
        ingredients: "Plat du jour, boisson chaude, fruit de saison",
        allergens: "Variable selon le menu du jour",
        tone: "#ffe9a3",
      },
      {
        id: "fe-2",
        name: "Formule Lunch Solo",
        description: "Un plat chaud du jour, un jus naturel 50 cl et un dessert.",
        price: 5000,
        category: "Formules solo",
        grams: 750,
        kcal: 950,
        ingredients: "Plat du jour, jus naturel, dessert",
        allergens: "Variable selon le menu du jour",
        tone: "#ffd9b0",
      },
      {
        id: "fe-3",
        name: "Formule Duo Journée",
        description: "Petit-déjeuner + déjeuner pour une personne, deux livraisons dans la journée.",
        price: 7500,
        oldPrice: 8000,
        category: "Formules solo",
        grams: 1200,
        kcal: 1560,
        ingredients: "Petit-déjeuner complet, plat chaud, jus naturel",
        allergens: "Variable selon le menu du jour",
        tone: "#e9edff",
      },
      {
        id: "fe-4",
        name: "Pack Équipe 10 personnes",
        description: "Dix déjeuners au choix, livrés ensemble, avec couverts et serviettes.",
        price: 45000,
        oldPrice: 50000,
        category: "Formules équipe",
        grams: 6500,
        kcal: 8900,
        ingredients: "10 plats au choix, 10 jus naturels",
        allergens: "Variable selon les plats choisis",
        tone: "#e6f5e2",
      },
      {
        id: "fe-5",
        name: "Pack Réunion",
        description: "Plateau de canapés, mini-viennoiseries et jus, pour vos réunions clients.",
        price: 30000,
        category: "Réunions",
        grams: 4000,
        kcal: 5200,
        ingredients: "Canapés variés, viennoiseries, jus naturels",
        allergens: "Gluten, œufs, lait, poisson",
        tone: "#ffe0e0",
      },
      {
        id: "fe-6",
        name: "Pause café entreprise",
        description: "Café, thé, jus et snacks sucrés-salés installés dans votre salle de pause.",
        price: 25000,
        category: "Pauses café",
        grams: 3500,
        kcal: 4100,
        ingredients: "Café, thé, jus, snacks sucrés et salés",
        allergens: "Gluten, lait, arachides",
        tone: "#efe4d8",
      },
      {
        id: "fe-7",
        name: "Abonnement mensuel 20 jours",
        description: "Un déjeuner par jour ouvré pendant un mois, menu différent chaque jour.",
        price: 90000,
        oldPrice: 100000,
        category: "Abonnements",
        grams: 11000,
        kcal: 17000,
        ingredients: "20 déjeuners complets au choix",
        allergens: "Variable selon le menu du jour",
        tone: "#f3e6ff",
      },
      {
        id: "fe-8",
        name: "Formule végétarienne",
        description: "Menu 100 % végétarien, décliné chaque jour selon le marché.",
        price: 4500,
        category: "Végétarien",
        grams: 600,
        kcal: 640,
        ingredients: "Légumes de saison, féculents, jus naturel",
        allergens: "Variable selon le menu du jour",
        tone: "#e2f3f5",
      },
    ],
  },
  {
    slug: "traiteur",
    name: "Traiteur & événements",
    kind: "Service traiteur",
    address: "Douala et environs",
    availability: "Sur devis, 48h à l'avance",
    rating: 98,
    ratingLabel: "Parfait",
    time: "Sur devis",
    fee: "Gratuite",
    intro:
      "Mariages, séminaires, anniversaires : nous cuisinons, dressons et servons pour vos invités.",
    categories: ["Buffets", "Cocktails", "Brochettes", "Desserts", "Boissons", "Mariages", "Séminaires"],
    tone: "from-[#ffe0e0] to-[#ffb3b3]",
    swatch: "#ffe0e0",
    products: [
      {
        id: "tr-1",
        name: "Buffet cocktail 20 personnes",
        description: "Assortiment de canapés, brochettes et mini-plats chauds pour vingt invités.",
        price: 120000,
        oldPrice: 135000,
        category: "Cocktails",
        grams: 9000,
        kcal: 14000,
        ingredients: "Canapés, brochettes, mini-plats chauds, sauces maison",
        allergens: "Gluten, œufs, lait, poisson, arachides",
        tone: "#ffe0e0",
      },
      {
        id: "tr-2",
        name: "Plateau de canapés (50 pièces)",
        description: "Cinquante bouchées froides variées, dressées sur plateau prêt à servir.",
        price: 35000,
        category: "Cocktails",
        grams: 2500,
        kcal: 4200,
        ingredients: "Pain de mie, saumon, poulet, fromage, légumes",
        allergens: "Gluten, poisson, lait",
        tone: "#ffdca8",
      },
      {
        id: "tr-3",
        name: "Brochettes party (50 pièces)",
        description: "Brochettes de bœuf et de poulet marinées, grillées sur place si vous le souhaitez.",
        price: 50000,
        oldPrice: 55000,
        category: "Brochettes",
        grams: 4000,
        kcal: 6800,
        ingredients: "Bœuf, poulet, poivron, oignon, épices maison",
        allergens: "Moutarde, soja",
        tone: "#ffd3c2",
      },
      {
        id: "tr-4",
        name: "Buffet mariage 100 personnes",
        description: "Buffet complet, entrées, plats locaux et internationaux, desserts et service.",
        price: 750000,
        category: "Mariages",
        grams: 45000,
        kcal: 68000,
        ingredients: "Menu personnalisé avec les mariés",
        allergens: "Variable selon le menu retenu",
        tone: "#f3e6ff",
      },
      {
        id: "tr-5",
        name: "Coffee break séminaire",
        description: "Deux pauses café dans la journée, viennoiseries, fruits et jus naturels.",
        price: 60000,
        oldPrice: 68000,
        category: "Séminaires",
        grams: 8000,
        kcal: 9600,
        ingredients: "Café, thé, viennoiseries, fruits, jus naturels",
        allergens: "Gluten, lait, œufs",
        tone: "#efe4d8",
      },
      {
        id: "tr-6",
        name: "Pack anniversaire enfant",
        description: "Mini-sandwichs, jus, gâteau personnalisé et petites douceurs.",
        price: 85000,
        category: "Desserts",
        grams: 7000,
        kcal: 11000,
        ingredients: "Sandwichs, gâteau, jus, bonbons",
        allergens: "Gluten, œufs, lait, arachides",
        tone: "#ffd0d8",
      },
      {
        id: "tr-7",
        name: "Fontaine à jus (10 L)",
        description: "Dix litres de jus naturel au parfum de votre choix, fontaine incluse.",
        price: 45000,
        category: "Boissons",
        grams: 10000,
        kcal: 4200,
        ingredients: "Jus naturels au choix",
        allergens: "Aucun",
        tone: "#ffe9a3",
      },
      {
        id: "tr-8",
        name: "Buffet dessert 30 personnes",
        description: "Verrines, salade de fruits, mini-gâteaux et beignets sucrés.",
        price: 90000,
        oldPrice: 98000,
        category: "Desserts",
        grams: 6000,
        kcal: 9800,
        ingredients: "Fruits, crème, farine, œufs, chocolat",
        allergens: "Gluten, œufs, lait, fruits à coque",
        tone: "#f7e0c0",
      },
    ],
  },
];

export function getMenu(slug: string): Menu | undefined {
  return MENUS.find((menu) => menu.slug === slug);
}

export function allProducts(): { product: Product; menu: Menu }[] {
  return MENUS.flatMap((menu) => menu.products.map((product) => ({ product, menu })));
}

export function findProduct(id: string) {
  return allProducts().find((entry) => entry.product.id === id);
}

export const ORDER_STEPS = [
  "Commande confirmée",
  "En préparation",
  "En attente du livreur",
  "En route",
  "Livrée",
];
